In [38]:
#coding: utf-8
from bs4 import BeautifulSoup
import requests
from urllib.request import urlopen
from urllib.parse import urlparse
import datetime
import random
import re
from gtts import gTTS
import time
import sys
import numpy as np
import math
import json
from io import StringIO
import os 
import vis
import matplotlib.pyplot as plt

keyword=sys.argv[1]


def getPage(url):
    """
    Utilty function used to get a Beautiful Soup object from a given URL
    """

    session = requests.Session()
    headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36',
               'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'}
    try:
        req = session.get(url, headers=headers)
    except requests.exceptions.RequestException:
        return None
    bs = BeautifulSoup(req.text, 'html.parser')
    return bs

def scrapeHiStock(url):
    bs = getPage(url)
    title=bs.find("table", class_="gvTB")
    lines = bs.select('div mainmainBG pb10')
    body = '\n'.join([line.text for line in lines])
    num_stock = title.find('a').string
    
    return url, title, body

def scrapeHiStockSamp(num): 
    url = 'https://histock.tw/stock/' + str(num)  
    session = requests.Session()
    headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36',
               'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'}
    try:
        req = session.get(url, headers=headers)
    except requests.exceptions.RequestException:
        return None
    root = BeautifulSoup(req.text, 'html.parser')
    deal=root.findAll("span", class_="clr-gr")
    add=root.findAll("span", class_="clr-rd")
    return root, deal, add

def scrapeHiStockNo(url, num):
    bs = getPage(url)
    i=0
    for title in bs.findAll("table", class_="gvTB"):
        if(i == num):
            break
        i = i + 1
    lines = bs.select('div mainmainBG pb10')
    body = '\n'.join([line.text for line in lines])
    num_stock = title.find('a').string
    return url, title, body
def write_json(new_data, filename='data.json'):
    with open(filename,'r+') as file:
          # First we load existing data into a dict.
        file_data = json.load(file)
        # Join new_data with file_data inside emp_details
        file_data["emp_details"].append(new_data)
        # Sets file's current position at offset.
        file.seek(0)
        # convert back to json.
        json.dump(file_data, file, indent = 4)

def stock_update(x, new_val):
    for i in range(len(x)-1):
        x[len(x)-i-1] = x[len(x)-i-2]
    x[0]=new_val
    return x


In [39]:
def scrapeYahooStock(num): 
    url = 'https://tw.stock.yahoo.com/q/bc?s=' + str(num)  
    session = requests.Session()
    headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36',
               'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'}
    try:
        req = session.get(url, headers=headers)
    except requests.exceptions.RequestException:
        return None
    root = BeautifulSoup(req.text, 'html.parser')
    
    return root

root = scrapeYahooStock(2344)

In [40]:
num=2344
root, deal, add= scrapeHiStockSamp(num)


In [50]:
mat = np.zeros((100,1))
mat[0]=float(add[0].string)
stock_update(mat, float(add[0].string))

ValueError: could not convert string to float: '+1%'

In [46]:
x = np.zeros((100,1))
y = np.ones((100,1))
for i in range(100):
    y[i] = float(i) * y[i]
print(y)


wishlist=[2330]
while (1):
    for num in wishlist:
        root, deal, add= scrapeHiStockSamp(num)
        #root
        str_price = root.find("span", class_="clr-rd")
        new_price = float(str_price.string)
        x = stock_update(x, new_price)
        plt.plot(x, y)
    os.system('sleep 1')
    

[[ 0.]
 [ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]
 [11.]
 [12.]
 [13.]
 [14.]
 [15.]
 [16.]
 [17.]
 [18.]
 [19.]
 [20.]
 [21.]
 [22.]
 [23.]
 [24.]
 [25.]
 [26.]
 [27.]
 [28.]
 [29.]
 [30.]
 [31.]
 [32.]
 [33.]
 [34.]
 [35.]
 [36.]
 [37.]
 [38.]
 [39.]
 [40.]
 [41.]
 [42.]
 [43.]
 [44.]
 [45.]
 [46.]
 [47.]
 [48.]
 [49.]
 [50.]
 [51.]
 [52.]
 [53.]
 [54.]
 [55.]
 [56.]
 [57.]
 [58.]
 [59.]
 [60.]
 [61.]
 [62.]
 [63.]
 [64.]
 [65.]
 [66.]
 [67.]
 [68.]
 [69.]
 [70.]
 [71.]
 [72.]
 [73.]
 [74.]
 [75.]
 [76.]
 [77.]
 [78.]
 [79.]
 [80.]
 [81.]
 [82.]
 [83.]
 [84.]
 [85.]
 [86.]
 [87.]
 [88.]
 [89.]
 [90.]
 [91.]
 [92.]
 [93.]
 [94.]
 [95.]
 [96.]
 [97.]
 [98.]
 [99.]]


ValueError: could not convert string to float: '+1%'

i = 0
root, deal, add= scrapeHiStockSamp(num)
str_price = root.findAll("span", class_="clr-gr")
print(str_price[].string)
plt.plot(i, float(str_price))
i = i + 1

In [90]:
def get_price(root):
    stock2 = root.findAll("meta")
    string = str(stock2[7])
    txt=re.split(r',',string)
    sngstr = txt[1]
    print(sngstr)
    price_str = re.sub(r'[股價| ]','', sngstr)
    price = float(price_str)
    print(price)
    return price

In [91]:
i = 0

In [ ]:
print(num)
mat_x = range(len(mat))
while 1:
    root, deal, add= scrapeHiStockSamp(num)
    price = get_price(root)
    stock_update(mat, price)
    print(mat)
    os.system('sleep 5')


2330
 股價 596
596.0
[[596.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]]
 股價 596
596.0
[[596.]
 [596.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [ 

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]
 [  0.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5

 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]]
 股價 596
596.0
[[596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [596.]
 [5